// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/quadroops/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// EventProvider is an autogenerated mock type for the EventProvider type
type EventProvider struct {
	mock.Mock
}

// Provide provides a mock function with given fields:
func (_m *EventProvider) Provide() <-chan *domain.EventMessage {
	ret := _m.Called()

	var r0 <-chan *domain.EventMessage
	if rf, ok := ret.Get(0).(func() <-chan *domain.EventMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *domain.EventMessage)
		}
	}

	return r0
}
