// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/quadroops/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

// RandomString provides a mock function with given fields:
func (_m *Generator) RandomString() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UID provides a mock function with given fields:
func (_m *Generator) UID() (domain.UID, error) {
	ret := _m.Called()

	var r0 domain.UID
	if rf, ok := ret.Get(0).(func() domain.UID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.UID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
